FROM ubuntu:16.04
LABEL maintainer "Yovi Oktofianus <yovio@yahoo.com>"

ENV DEBIAN_FRONTEND noninteractive

#password for Wordpress db
ENV WP_DB_PASS Password 

#Environment variables to configure php
ENV PHP_UPLOAD_MAX_FILESIZE 10M
ENV PHP_POST_MAX_SIZE 10M

RUN apt-get update && \
  apt-get -y install supervisor git pwgen mariadb-server curl apache2 && \
  apt-get -y install php libapache2-mod-php php-mcrypt php-mysql php-curl php-gd php-mbstring php-xml php-xmlrpc && \
  echo "ServerName localhost" >> /etc/apache2/apache2.conf
  
  
# Add image configuration and scripts
COPY script /script

RUN find /script -type f -name "*.sh" -exec chmod 755 {} \;
RUN cp /script/apache/supervisord-apache2.conf /etc/supervisor/conf.d/supervisord-apache2.conf
RUN cp /script/mysql/supervisord-mysqld.conf /etc/supervisor/conf.d/supervisord-mysqld.conf
RUN cp /script/apache/apache_default /etc/apache2/sites-available/000-default.conf

# Remove pre-installed database
RUN rm -rf /var/lib/mysql/*
RUN a2enmod rewrite

RUN /script/wordpress/deploy_wordpress.sh
RUN /script/gateone/deploy_gateone.sh
  
VOLUME  ["/etc/mysql", "/var/lib/mysql" ]

# 8080 for guacamole, 8081 for gateone, 8082 for wordpress
EXPOSE 8080, 8081, 8082
CMD ["/script/run.sh"]