version: "2"
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inside
    volumes:
     - /docker-data/mysql/data:/var/lib/mysql # Location of MariaDB/Mysql data files
    restart: always
  influxdb:
    container_name: influxdb
    image: influxdb:alpine
    networks:
      - inside
    volumes:
     - /docker-data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro # Location of influxdb conf file
     - /docker-data/influxdb/data:/var/lib/influxdb
    restart: always

networks:
  inside:
    external:
      name: bridge-inside