version: "2"
services:  
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - inside
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=grafana.yovi.info
      - LETSENCRYPT_HOST=grafana.yovi.info
      - LETSENCRYPT_EMAIL=yovio@hotmail.com
    env_file:
     - /docker-data/env-files/grafana.env
    volumes:
     - /docker-data/grafana:/var/lib/grafana # Location of grafana data
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    networks:
      - inside
    ports:
      - "15672:15672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
    env_file:
     - /docker-data/env-files/rabbitmq.env
    volumes:
     - /docker-data/rabbitmq:/var/lib/rabbitmq # Location of rabbitmq data
    restart: always

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - inside
    ports:
      - "6379:6379"
    volumes:
     - /docker-data/redis/data:/data # Location of redis data
     - /docker-data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    command: sh -c 'redis-server /usr/local/etc/redis/redis.conf'

  webhook:
    container_name: webhook
    image: yovio/docker-webhook
    networks:
      - inside
    expose:
     - 8555
    environment:
      - VIRTUAL_PORT=8555
      - VIRTUAL_HOST=docker-webhook.yovi.info
      - LETSENCRYPT_HOST=docker-webhook.yovi.info
      - LETSENCRYPT_EMAIL=yovio@hotmail.com    
    volumes:
     - /docker-data/webhook/scripts:/dockerpuller/scripts
     - /docker-data/webhook/config.json:/dockerpuller/config.json:ro
     - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  inside:
    external:
      name: bridge-inside