FROM ubuntu:16.04
LABEL maintainer "Yovi Oktofianus <yovio@yahoo.com>"

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
  apt-get -y install supervisor git pwgen mariadb-server curl apache2 && \
  apt-get -y install php libapache2-mod-php php-mcrypt php-mysql php-curl php-gd php-mbstring php-xml php-xmlrpc && \
  echo "ServerName localhost" >> /etc/apache2/apache2.conf
  
  
# Add image configuration and scripts
COPY script /tmp/script

RUN find /tmp/script -type f -name "*.sh" -exec chmod 755 {} \;
RUN cp /tmp/script/apache/supervisord-apache2.conf /etc/supervisor/conf.d/supervisord-apache2.conf
RUN cp /tmp/script/mysql/supervisord-mysqld.conf /etc/supervisor/conf.d/supervisord-mysqld.conf
RUN cp /tmp/script/apache/apache_default /etc/apache2/sites-available/000-default.conf

# Remove pre-installed database
RUN rm -rf /var/lib/mysql/*

RUN /tmp/script/wordpress/deploy_wordpress.sh

RUN a2enmod rewrite
  
#Environment variables to configure php
ENV PHP_UPLOAD_MAX_FILESIZE 10M
ENV PHP_POST_MAX_SIZE 10M
  
VOLUME  ["/etc/mysql", "/var/lib/mysql" ]

EXPOSE 80 443
CMD ["/run.sh"]