version: "2"
services:  
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - inside
    env_file:
     - /docker-data/env-files/grafana.env
    volumes:
     - /docker-data/grafana:/var/lib/grafana # Location of grafana data
    restart: always
    

networks:
  inside:
    external:
      name: bridge-inside