version: "2"
services:  
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - inside
    env_file:
     - /docker-data/env-files/grafana.env
    volumes:
     - /docker-data/grafana/plugins:/var/lib/grafana/plugins # Location of influxdb conf file
    restart: always
    
  cadvisor:
    image: google/cadvisor
    container_name:cadvisor
    networks:
     - inside
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
    restart: always
    ports:
     - "8080:8080"
    volumes:
     - /:/rootfs:ro
     - /var/run:/var/run:rw
     - /sys:/sys:ro
     - /var/lib/docker/:/var/lib/docker:ro

networks:
  inside:
    external:
      name: bridge-inside