version: "2"
services:  
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - inside
    env_file:
     - /docker-data/env-files/grafana.env
    volumes:
     - /docker-data/grafana/plugins:/var/lib/grafana/plugins # Location of influxdb conf file
    restart: always

networks:
  inside:
    external:
      name: bridge-inside